### ISSUE TITLE
GetLLM bugs in compensate_exitation and beta from amplitude

### ISSUE THREAD

**Issue by elenafol** [pylhc/Beta-Beat.src#76] opened 2018-02-14 13:41 UTC
Running GetLlm roduces following errors: 

**in compensate_excitations.py:**
14:32:11 - GetLlm STDERR:   File "/afs/cern.ch/work/e/efol/public/betaBeat_master/Beta-Beat.src/GetLLM/algorithms/compensate_excitation.py", line 404, in GetFreeCoupling_Eq
14:32:11 - GetLlm STDERR:     psih = psih - (psih[k_bpmac_h] - psid_ac2bpmac_h) # OK, untill here, it is Psi(s, s_ac)
14:32:11 - GetLlm STDERR: IndexError: index 101 is out of bounds for axis 0 with size 95

**GetLLM.algorithms.interaction_point:**
ERROR | <function format_exc at 0x7fc2d27ca5f0> | .GetLLM 
/afs/cern.ch/work/o/omc/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice. 

**command:** 
/afs/cern.ch/work/o/omc/anaconda/bin/python /home/efol/work/public/betaBeat_master/Beta-Beat.src/GetLLM/GetLLM.py --accel=LHCB1 --model=/afs/cern.ch/work/e/efol/public/betabeatGui/temp/2018-02-14/models/LHCB1/flatModel_test2/twiss.dat --files=/afs/cern.ch/work/e/efol/public/betabeatGui/temp/2018-02-14/LHCB1/Measurements/Beam1@Turn@2017_12_01@18_32_53_504/Beam1@Turn@2017_12_01@18_32_53_504.sdds --output=/afs/cern.ch/work/e/efol/public/betabeatGui/temp/2018-02-14/LHCB1/Results/getLmmNew_test2 --tbtana=SUSSIX --bpmu=mm --lhcphase=1 --errordefs=/afs/cern.ch/work/e/efol/public/betabeatGui/temp/2018-02-14/models/LHCB1/flatModel_test2/error_deff.txt

**Comment by awegsche** [comment] 2018-02-15 15:48
the problem is that the nearest exciter BPMs for AC-dipole only exist in one plane and for coupling we take the intersection of x and y plane. 

there are 2 solutions:
- looking for a close BPM in the intersection (which then is not that close anymore)
- treat the two planes independently untile the phase reconstruction is made (if this is possible)

I will investigate this

**Comment by awegsche** [comment] 2018-03-28 10:25
I will close this because the problem is treated in a dedicated issue, #109

**Closed by awegsche** 2018-03-28 10:25 UTC
Labels: bug, getllm
